const imoveis = [
  {
    endereco: "Rua A, 100",
    estado: "Rio de Janeiro",
    cidade: "Rio de Janeiro",
    corretor_responsavel: "Carlos Silva",
    proprietario: "Ana Costa",
    valor_do_imovel: 500000,
  },
  {
    endereco: "Avenida B, 200",
    estado: "Rio de Janeiro",
    cidade: "Niterói",
    corretor_responsavel: "João Pereira",
    proprietario: "José Santos",
    valor_do_imovel: 400000,
  },
  {
    endereco: "Rua C, 300",
    estado: "Rio de Janeiro",
    cidade: "Campos dos Goytacazes",
    corretor_responsavel: "Luciana Almeida",
    proprietario: "Pedro Oliveira",
    valor_do_imovel: 350000,
  },
  {
    endereco: "Avenida D, 400",
    estado: "Rio de Janeiro",
    cidade: "Duque de Caxias",
    corretor_responsavel: "Fernanda Lima",
    proprietario: "Marcos Souza",
    valor_do_imovel: 450000,
  },
  {
    endereco: "Rua E, 500",
    estado: "Rio de Janeiro",
    cidade: "São Gonçalo",
    corretor_responsavel: "Rafael Silva",
    proprietario: "Paula Alves",
    valor_do_imovel: 550000,
  },
  {
    endereco: "Rua F, 600",
    estado: "Rio de Janeiro",
    cidade: "Macaé",
    corretor_responsavel: "Cláudia Costa",
    proprietario: "Ricardo Lima",
    valor_do_imovel: 600000,
  },
  {
    endereco: "Avenida G, 700",
    estado: "Rio de Janeiro",
    cidade: "Volta Redonda",
    corretor_responsavel: "Mariana Oliveira",
    proprietario: "Felipe Almeida",
    valor_do_imovel: 380000,
  },
  {
    endereco: "Rua H, 800",
    estado: "Rio de Janeiro",
    cidade: "Belford Roxo",
    corretor_responsavel: "Paulo Silva",
    proprietario: "Isabela Ferreira",
    valor_do_imovel: 420000,
  },
  {
    endereco: "Avenida I, 900",
    estado: "Rio de Janeiro",
    cidade: "Nova Iguaçu",
    corretor_responsavel: "Juliana Santos",
    proprietario: "Vinícius Martins",
    valor_do_imovel: 470000,
  },
  {
    endereco: "Rua J, 1000",
    estado: "Rio de Janeiro",
    cidade: "Cabo Frio",
    corretor_responsavel: "Thiago Almeida",
    proprietario: "Camila Rocha",
    valor_do_imovel: 650000,
  },
  {
    endereco: "Rua K, 1100",
    estado: "Rio de Janeiro",
    cidade: "Angra dos Reis",
    corretor_responsavel: "André Costa",
    proprietario: "Ricardo Santos",
    valor_do_imovel: 700000,
  },
  {
    endereco: "Avenida L, 1200",
    estado: "Rio de Janeiro",
    cidade: "Macaé",
    corretor_responsavel: "Larissa Ferreira",
    proprietario: "Mariana Oliveira",
    valor_do_imovel: 480000,
  },
  {
    endereco: "Rua M, 1300",
    estado: "Rio de Janeiro",
    cidade: "Petropólis",
    corretor_responsavel: "Gustavo Lima",
    proprietario: "João Pedro Silva",
    valor_do_imovel: 550000,
  },
  {
    endereco: "Avenida N, 1400",
    estado: "Rio de Janeiro",
    cidade: "Itaperuna",
    corretor_responsavel: "Bruna Lima",
    proprietario: "Marcos Fernandes",
    valor_do_imovel: 380000,
  },
  {
    endereco: "Rua O, 1500",
    estado: "Rio de Janeiro",
    cidade: "Resende",
    corretor_responsavel: "Ricardo Costa",
    proprietario: "Fernanda Souza",
    valor_do_imovel: 460000,
  },
  {
    endereco: "Avenida P, 1600",
    estado: "Rio de Janeiro",
    cidade: "Teresópolis",
    corretor_responsavel: "Alessandra Pereira",
    proprietario: "Eduardo Silva",
    valor_do_imovel: 530000,
  },
  {
    endereco: "Rua Q, 1700",
    estado: "Rio de Janeiro",
    cidade: "Rio das Ostras",
    corretor_responsavel: "Mariana Lima",
    proprietario: "Bruna Costa",
    valor_do_imovel: 590000,
  },
  {
    endereco: "Avenida R, 1800",
    estado: "Rio de Janeiro",
    cidade: "Barra Mansa",
    corretor_responsavel: "Fábio Costa",
    proprietario: "Tiago Santos",
    valor_do_imovel: 400000,
  },
  {
    endereco: "Rua S, 1900",
    estado: "Rio de Janeiro",
    cidade: "São João de Meriti",
    corretor_responsavel: "Roberta Souza",
    proprietario: "Marcos Pereira",
    valor_do_imovel: 370000,
  },
  {
    endereco: "Avenida T, 2000",
    estado: "Rio de Janeiro",
    cidade: "Magé",
    corretor_responsavel: "Gabriel Oliveira",
    proprietario: "Sofia Martins",
    valor_do_imovel: 420000,
  },
  {
    endereco: "Rua U, 2100",
    estado: "Rio de Janeiro",
    cidade: "Nilópolis",
    corretor_responsavel: "Luiza Rocha",
    proprietario: "João Costa",
    valor_do_imovel: 450000,
  },
  {
    endereco: "Avenida V, 2200",
    estado: "Rio de Janeiro",
    cidade: "Cachoeiras de Macacu",
    corretor_responsavel: "Thiago Pereira",
    proprietario: "Isabela Santos",
    valor_do_imovel: 380000,
  },
  {
    endereco: "Rua W, 2300",
    estado: "Rio de Janeiro",
    cidade: "Volta Redonda",
    corretor_responsavel: "Gabriel Souza",
    proprietario: "Mariana Almeida",
    valor_do_imovel: 510000,
  },
  {
    endereco: "Avenida X, 2400",
    estado: "Rio de Janeiro",
    cidade: "Araruama",
    corretor_responsavel: "Carlos Oliveira",
    proprietario: "Paula Lima",
    valor_do_imovel: 580000,
  },
  {
    endereco: "Rua Y, 2500",
    estado: "Rio de Janeiro",
    cidade: "São Gonçalo",
    corretor_responsavel: "Juliana Costa",
    proprietario: "Ricardo Pereira",
    valor_do_imovel: 500000,
  },
  {
    endereco: "Avenida Z, 2600",
    estado: "Rio de Janeiro",
    cidade: "Angra dos Reis",
    corretor_responsavel: "Larissa Costa",
    proprietario: "José Oliveira",
    valor_do_imovel: 720000,
  },
  {
    endereco: "Rua AA, 2700",
    estado: "Rio de Janeiro",
    cidade: "Macaé",
    corretor_responsavel: "Vinícius Silva",
    proprietario: "Fernanda Almeida",
    valor_do_imovel: 490000,
  },
  {
    endereco: "Avenida AB, 2800",
    estado: "Rio de Janeiro",
    cidade: "Cabo Frio",
    corretor_responsavel: "Cláudia Lima",
    proprietario: "Luana Santos",
    valor_do_imovel: 620000,
  },
  {
    endereco: "Rua AC, 2900",
    estado: "Rio de Janeiro",
    cidade: "Campos dos Goytacazes",
    corretor_responsavel: "Gustavo Almeida",
    proprietario: "Paulo Costa",
    valor_do_imovel: 430000,
  },
  {
    endereco: "Avenida AD, 3000",
    estado: "Rio de Janeiro",
    cidade: "Itaperuna",
    corretor_responsavel: "Marcos Pereira",
    proprietario: "Sofia Rocha",
    valor_do_imovel: 370000,
  },
  {
    endereco: "Rua AE, 3100",
    estado: "Rio de Janeiro",
    cidade: "Teresópolis",
    corretor_responsavel: "Bruna Oliveira",
    proprietario: "Carlos Souza",
    valor_do_imovel: 550000,
  },
  {
    endereco: "Avenida AF, 3200",
    estado: "Rio de Janeiro",
    cidade: "Niterói",
    corretor_responsavel: "Luciana Ferreira",
    proprietario: "Mário Pereira",
    valor_do_imovel: 490000,
  },
  {
    endereco: "Rua AG, 3300",
    estado: "Rio de Janeiro",
    cidade: "Belford Roxo",
    corretor_responsavel: "Ricardo Almeida",
    proprietario: "João Alves",
    valor_do_imovel: 420000,
  },
  {
    endereco: "Avenida AH, 3400",
    estado: "Rio de Janeiro",
    cidade: "Volta Redonda",
    corretor_responsavel: "Mariana Costa",
    proprietario: "Pedro Rocha",
    valor_do_imovel: 460000,
  },
  {
    endereco: "Rua AI, 3500",
    estado: "Rio de Janeiro",
    cidade: "Magé",
    corretor_responsavel: "Gabriel Lima",
    proprietario: "Carlos Martins",
    valor_do_imovel: 440000,
  },
  {
    endereco: "Avenida AJ, 3600",
    estado: "Rio de Janeiro",
    cidade: "Macaé",
    corretor_responsavel: "Cláudia Pereira",
    proprietario: "Paulo Lima",
    valor_do_imovel: 590000,
  },
  {
    endereco: "Rua L, 1200",
    estado: "São Paulo",
    cidade: "São Paulo",
    corretor_responsavel: "Júlia Oliveira",
    proprietario: "Luís Souza",
    valor_do_imovel: 850000,
  },
  {
    endereco: "Avenida M, 1300",
    estado: "Minas Gerais",
    cidade: "Belo Horizonte",
    corretor_responsavel: "Amanda Silva",
    proprietario: "Gabriel Rocha",
    valor_do_imovel: 720000,
  },
  {
    endereco: "Rua N, 1400",
    estado: "Bahia",
    cidade: "Salvador",
    corretor_responsavel: "Ricardo Pereira",
    proprietario: "Fernanda Lima",
    valor_do_imovel: 640000,
  },
  {
    endereco: "Avenida O, 1500",
    estado: "Santa Catarina",
    cidade: "Florianópolis",
    corretor_responsavel: "Laura Costa",
    proprietario: "Carlos Martins",
    valor_do_imovel: 790000,
  },
  {
    endereco: "Rua P, 1600",
    estado: "Paraná",
    cidade: "Curitiba",
    corretor_responsavel: "Gustavo Almeida",
    proprietario: "Sofia Ferreira",
    valor_do_imovel: 670000,
  },
  {
    endereco: "Avenida Q, 1700",
    estado: "Rio Grande do Sul",
    cidade: "Porto Alegre",
    corretor_responsavel: "André Lima",
    proprietario: "Beatriz Silva",
    valor_do_imovel: 730000,
  },
  {
    endereco: "Rua R, 1800",
    estado: "Ceará",
    cidade: "Fortaleza",
    corretor_responsavel: "Larissa Rocha",
    proprietario: "José Costa",
    valor_do_imovel: 560000,
  },
  {
    endereco: "Avenida S, 1900",
    estado: "Pernambuco",
    cidade: "Recife",
    corretor_responsavel: "Rafael Santos",
    proprietario: "Maria Souza",
    valor_do_imovel: 600000,
  },
  {
    endereco: "Rua T, 2000",
    estado: "Espírito Santo",
    cidade: "Vitória",
    corretor_responsavel: "Paula Lima",
    proprietario: "Ricardo Alves",
    valor_do_imovel: 700000,
  },
  {
    endereco: "Avenida U, 2100",
    estado: "Maranhão",
    cidade: "São Luís",
    corretor_responsavel: "João Costa",
    proprietario: "Cláudia Oliveira",
    valor_do_imovel: 450000,
  },
  {
    endereco: "Rua V, 2200",
    estado: "Goiás",
    cidade: "Goiânia",
    corretor_responsavel: "Marcos Silva",
    proprietario: "Renata Pereira",
    valor_do_imovel: 620000,
  },
  {
    endereco: "Avenida W, 2300",
    estado: "Alagoas",
    cidade: "Maceió",
    corretor_responsavel: "Fernanda Costa",
    proprietario: "Juliana Souza",
    valor_do_imovel: 550000,
  },
  {
    endereco: "Rua X, 2400",
    estado: "Acre",
    cidade: "Rio Branco",
    corretor_responsavel: "Carlos Almeida",
    proprietario: "Paula Rocha",
    valor_do_imovel: 400000,
  },
  {
    endereco: "Avenida Y, 2500",
    estado: "Amazonas",
    cidade: "Manaus",
    corretor_responsavel: "Cláudia Rocha",
    proprietario: "Gustavo Alves",
    valor_do_imovel: 490000,
  },
  {
    endereco: "Rua Z, 2600",
    estado: "Rondônia",
    cidade: "Porto Velho",
    corretor_responsavel: "Juliana Oliveira",
    proprietario: "Ricardo Rocha",
    valor_do_imovel: 520000,
  },
  {
    endereco: "Avenida AA, 2700",
    estado: "Tocantins",
    cidade: "Palmas",
    corretor_responsavel: "Rafael Almeida",
    proprietario: "Ana Souza",
    valor_do_imovel: 480000,
  },
  {
    endereco: "Rua AB, 2800",
    estado: "Distrito Federal",
    cidade: "Brasília",
    corretor_responsavel: "Gustavo Lima",
    proprietario: "Luciana Santos",
    valor_do_imovel: 1000000,
  },
  {
    endereco: "Avenida AC, 2900",
    estado: "Paraíba",
    cidade: "João Pessoa",
    corretor_responsavel: "Lúcia Oliveira",
    proprietario: "Tiago Costa",
    valor_do_imovel: 600000,
  },
  {
    endereco: "Rua AD, 3000",
    estado: "Rio Grande do Norte",
    cidade: "Natal",
    corretor_responsavel: "Tiago Pereira",
    proprietario: "Eduardo Lima",
    valor_do_imovel: 650000,
  },
  {
    endereco: "Avenida AE, 3100",
    estado: "Sergipe",
    cidade: "Aracaju",
    corretor_responsavel: "Bruna Costa",
    proprietario: "Ricardo Almeida",
    valor_do_imovel: 590000,
  },
  {
    endereco: "Rua AF, 3200",
    estado: "Piauí",
    cidade: "Teresina",
    corretor_responsavel: "Carlos Souza",
    proprietario: "Maria Almeida",
    valor_do_imovel: 480000,
  },
  {
    endereco: "Avenida AG, 3300",
    estado: "Mato Grosso",
    cidade: "Cuiabá",
    corretor_responsavel: "Mariana Santos",
    proprietario: "Paulo Oliveira",
    valor_do_imovel: 670000,
  },
  {
    endereco: "Rua AH, 3400",
    estado: "Mato Grosso do Sul",
    cidade: "Campo Grande",
    corretor_responsavel: "Felipe Lima",
    proprietario: "Juliana Ferreira",
    valor_do_imovel: 600000,
  },
  {
    endereco: "Avenida AI, 3500",
    estado: "Pará",
    cidade: "Belém",
    corretor_responsavel: "Gustavo Pereira",
    proprietario: "Fernanda Lima",
    valor_do_imovel: 530000,
  },
  {
    endereco: "Rua AJ, 3600",
    estado: "Minas Gerais",
    cidade: "Uberlândia",
    corretor_responsavel: "Tiago Costa",
    proprietario: "Lucas Souza",
    valor_do_imovel: 600000,
  },
];
